version: "3.9"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"  # NameNode Web UI
      - "9000:9000"  # HDFS
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    depends_on:
      - namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - datanode-data:/hadoop/dfs/data
    networks:
      - hadoop

  pyspark-master:
    image: apache/spark:3.5.2
    container_name: pyspark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=pyspark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_UI_PORT=8080
      - SPARK_WORKER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master port
    networks:
      - hadoop

  pyspark-worker:
    image: apache/spark:3.5.2
    container_name: pyspark-worker
    depends_on:
      - pyspark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://pyspark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    ports:
      - "8081:8081"  # Worker Web UI
    networks:
      - hadoop

volumes:
  namenode-data:
  datanode-data:

networks:
  hadoop:
    driver: bridge
